# -*- coding: utf-8 -*-
"""Financial_Statement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E68BcnwrADx-SiTEjb96zxqBjap3ZnzP

# <center><h1>Financial Statement</h1></center>

# <h2>Load Libraries</h2>
"""

library(tidyverse)

"""#<h2>User Defined Functions</h2>

<h3><code>get_join_cols()</code></h3>
"""

get_join_cols <- function(round) {
    c(Tiers[round-1], Tiers[round])
}

"""<h3><code>create_row_mask()</code></h3>"""

create_row_mask <- function(df, round) {
    if(round==1) {
        mask <- filter(df, is.na(df[Tiers[round+1]]))
        mask[c(Tiers[round], "Descrição da Conta")]
    } else {
        join_cols <- get_join_cols(round)
        mask <- filter(df, is.na(df[Tiers[round+1]]))
        mask[append(join_cols, "Descrição da Conta")]
    }
}

"""<h3><code>left_join()</code> using '<code>dplyr::left_join()</code>'</h3>"""

left_join <- function(df, round, row_mask) {
    if(round==1) {
        df[Tiers[round]] <- dplyr::left_join(df[Tiers[round]], row_mask, by=Tiers[round])["Descrição da Conta"]
    } else{
        join_cols <- get_join_cols(round)
        df[Tiers[round]] <- dplyr::left_join(x=df[join_cols], y=row_mask, by=join_cols)["Descrição da Conta"]
    }
    df
}

"""<h3><code>left_join()</code> using '<code>merge()</code>'</h3>"""

left_join <- function(df, round, row_mask) {
    if(round==1) {
        df[Tiers[1]] <- merge(x=df[Tiers[1]], y=row_mask, by.x=Tiers[1], by.y=Tiers[1])["Descrição da Conta"]
    } else {
        merge_cols <- get_join_cols(round)
        df[Tiers[round]] <- merge(x=df[merge_cols], y=row_mask, by.x=merge_cols, by.y=merge_cols)["Descrição da Conta"]
    }
   df
}

"""<h3><code>drop_cols()</code> using '<code>[</code>'</h3>"""

drop_cols <- function(df, round) {

    column <- select(df, Tiers[round])

    condition1 <- column == select(df, "Descrição da Conta")

    vect <- pull(column)

    condition2 <- c()
    for(i in 1:(length(vect)-1)) {
    condition2[i] <- (vect[i] == vect[i+1])
        }
    condition2 <- append(condition2, FALSE)

    mask <- !(condition1 & condition2)

    df <- df[mask, colnames(df)]

}

"""<h3><code>drop_cols()</code> using '<code>subset()</code>'</h3>"""

drop_cols <- function(df, round) {

    column <- select(df, Tiers[round])

    condition1 <- column == select(df, "Descrição da Conta")

    vect <- pull(column)

    condition2 <- c()
    for(i in 1:(length(vect)-1)) {
    condition2[i] <- (vect[i] == vect[i+1])
        }
    condition2 <- append(condition2, FALSE)

    mask <- !(condition1 & condition2)

    df <- subset(df, mask)

}

"""<h3><code>drop_cols()</code> using '<code>filter()</code>'</h3>"""

drop_cols <- function(df, round) {

    column <- select(df, Tiers[round])

    condition1 <- column == select(df, "Descrição da Conta")

    vect <- pull(column)

    condition2 <- c()
    for(i in 1:(length(vect)-1)) {
    condition2[i] <- (vect[i] == vect[i+1])
        }
    condition2 <- append(condition2, FALSE)

    mask <- !(condition1 & condition2)

    df <- filter(df, mask)
}

"""#<h2>Import Data</h2>

<h3>Load .csv</h3>

<h4>base</h4>
"""

data_frame = read.csv2("Financial_Statement.csv")					#	use "read.csv2" if sep = ";". If sep = "," use "read.csv" instead
data_frame

"""<h3>Load .csv</h3>

<h4>using <code>readr</code></h4>
"""

data_frame <- read_delim("Financial_Statement.csv", delim=";")
data_frame

"""#<h2>Wrangling</h2>

# <h3>Separate</h3>
"""

Tiers = c("Tier1", "Tier2", "Tier3", "Tier4", "Tier5")

data_frame_sep <- separate(data=data_frame, col="Código da Conta", into=Tiers)
data_frame_sep

"""#<h3>First Round</h3>"""

round <- 1

"""<h4>Create Row Mask</h4>"""

row_mask <- create_row_mask(data_frame_sep, round)
row_mask

"""<h4>Left Join</h4>"""

data_frame_1 <- left_join(data_frame_sep, round, row_mask)
data_frame_1

"""<h4>Drop Columns:</h4>"""

data_frame_1 <- drop_cols(data_frame_1, round)
data_frame_1

"""#<h3>Second Round</h3>"""

round <- 2

"""<h4>Create Row Mask</h4>"""

row_mask <- create_row_mask(data_frame_1, round)
row_mask

"""<h4>Left Join</h4>"""

data_frame_2 <- left_join(data_frame_1, round, row_mask)
data_frame_2

"""<h4>Drop Columns:</h4>"""

data_frame_2 <- drop_cols(data_frame_2, round)
data_frame_2

"""#<h3>Third Round</h3>"""

round <- 3

"""<h4>Create Row Mask</h4>"""

row_mask <- create_row_mask(data_frame_2, round)
row_mask

"""<h4>Left Join</h4>"""

data_frame_3 <- left_join(data_frame_2, round, row_mask)
data_frame_3

"""<h4>Drop Columns:</h4>"""

data_frame_3 <- drop_cols(data_frame_3, round)
data_frame_3

"""#<h3>Fourth Round</h3>"""

round <- 4

"""<h4>Create Row Mask</h4>"""

row_mask <- create_row_mask(data_frame_3, round)
row_mask

"""<h4>Left Join</h4>"""

data_frame_4 <- left_join(data_frame_3, round, row_mask)
data_frame_4

"""<h4>Drop Columns:</h4>"""

data_frame_4 <- drop_cols(data_frame_4, round)
data_frame_4

"""#<h3>Fifth Round</h3>"""

data_frame_5 <- data_frame_4
data_frame_5[["Tier5"]] <- data_frame_5[["Descrição da Conta"]]
data_frame_5